// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Foo {
  payload: unknown
}

export function newFoo(): Foo {
  return {
    payload: null,
  }
}
