// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/**
 * Area is a physical site area.
 * Categories are denormalized for display.
 * (source: input.go)
 */
export interface Area {
  id: string
  /**
   * IANA timezone name.
   * Defaults from global settings.
   */
  timezone: string
  /** free-form note */
  note: string
}

export function newArea(): Area {
  return {
    id: '',
    timezone: '',
    note: '',
  }
}

/** (source: input.go) */
export interface Bare {
  a: string
}

export function newBare(): Bare {
  return {
    a: '',
  }
}
