// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: product.go) */
export interface Product {
  sku: string
}

export function newProduct(): Product {
  return {
    sku: '',
  }
}

/** (source: user.go) */
export interface User {
  name: string
}

export function newUser(): User {
  return {
    name: '',
  }
}
