// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Product {
  sku: string
}

export function newProduct(): Product {
  return {
    sku: '',
  }
}

export interface User {
  name: string
}

export function newUser(): User {
  return {
    name: '',
  }
}
