package gents_test

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/mmalcek/gents"
)

// ExampleGenerate shows the single-file entry point. A marked struct in
// the Go source produces one TS interface plus a factory function.
func ExampleGenerate() {
	dir, _ := os.MkdirTemp("", "gents-example-*")
	defer os.RemoveAll(dir)

	src := "package example\n\n" +
		"//gents:export\n" +
		"type User struct {\n" +
		"    ID   string `json:\"id\"`\n" +
		"    Name string `json:\"name\"`\n" +
		"}\n"
	path := filepath.Join(dir, "user.go")
	_ = os.WriteFile(path, []byte(src), 0o644)

	out, err := gents.Generate(path, gents.Options{})
	if err != nil {
		panic(err)
	}
	fmt.Print(out)
	// Output:
	// // Code generated by github.com/mmalcek/gents; DO NOT EDIT.
	//
	// export interface User {
	//   id: string
	//   name: string
	// }
	//
	// export function newUser(): User {
	//   return {
	//     id: '',
	//     name: '',
	//   }
	// }
}

// ExampleGenerateDir shows bundle mode: point gents at a directory tree
// and it collects every marked struct into a single TS output, with
// cross-file references resolving automatically.
func ExampleGenerateDir() {
	dir, _ := os.MkdirTemp("", "gents-example-*")
	defer os.RemoveAll(dir)

	userSrc := "package api\n\n" +
		"//gents:export\n" +
		"type User struct {\n" +
		"    Name    string  `json:\"name\"`\n" +
		"    Profile Profile `json:\"profile\"`\n" +
		"}\n"
	profileSrc := "package api\n\n" +
		"//gents:export\n" +
		"type Profile struct {\n" +
		"    Bio string `json:\"bio\"`\n" +
		"}\n"
	_ = os.WriteFile(filepath.Join(dir, "a_user.go"), []byte(userSrc), 0o644)
	_ = os.WriteFile(filepath.Join(dir, "b_profile.go"), []byte(profileSrc), 0o644)

	out, err := gents.GenerateDir(dir, gents.Options{})
	if err != nil {
		panic(err)
	}
	fmt.Print(out)
	// Output:
	// // Code generated by github.com/mmalcek/gents; DO NOT EDIT.
	//
	// export interface User {
	//   name: string
	//   profile: Profile
	// }
	//
	// export function newUser(): User {
	//   return {
	//     name: '',
	//     profile: newProfile(),
	//   }
	// }
	//
	// export interface Profile {
	//   bio: string
	// }
	//
	// export function newProfile(): Profile {
	//   return {
	//     bio: '',
	//   }
	// }
}
