// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Event {
  when: Date | null
}

export function newEvent(): Event {
  return {
    when: null,
  }
}
