// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Record {
  id: string
  maybe: string | null
  tags: string[]
  amount: string
}

export function newRecord(): Record {
  return {
    id: '',
    maybe: null,
    tags: [],
    amount: '',
  }
}
