// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Base {
  x: number
}

export function newBase(): Base {
  return {
    x: 0,
  }
}

export interface Foo {
  base: Base
  y: number
}

export function newFoo(): Foo {
  return {
    base: newBase(),
    y: 0,
  }
}
