// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Record {
  id: string
  maybe: string | null
  amount: string
}

export function newRecord(): Record {
  return {
    id: '',
    maybe: null,
    amount: '',
  }
}
