// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Foo {
  id: string
  n: number
  name: string
}

export function newFoo(): Foo {
  return {
    id: '',
    n: 0,
    name: '',
  }
}
