// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Outer {
  inner: Inner
}

export function newOuter(): Outer {
  return {
    inner: newInner(),
  }
}

/** (source: input.go) */
export interface Inner {
  value: string
}

export function newInner(): Inner {
  return {
    value: '',
  }
}
