// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Outer {
  inner: Inner
}

export function newOuter(): Outer {
  return {
    inner: newInner(),
  }
}

export interface Inner {
  value: string
}

export function newInner(): Inner {
  return {
    value: '',
  }
}
