// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Foo {
  data: string
  maybe: string | null
  bytes: string
}

export function newFoo(): Foo {
  return {
    data: '',
    maybe: null,
    bytes: '',
  }
}
