// Command gents reads Go source and writes a TypeScript file containing a
// matching interface + factory function for each struct marked with
// //gents:export.
//
// The -in flag accepts either a single Go file or a directory; gents
// figures out which by stat'ing the path. Directories are walked
// recursively (bundle mode). When -in is omitted, gents processes the
// current directory. -out is always required.
//
//	gents -out types.ts                    # bundle the current directory
//	gents -in api/ -out api.ts             # bundle a subtree
//	gents -in item.go -out item.ts         # single file
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/mmalcek/gents"
)

// generatedHeader is the exact first line gents writes. safeWrite uses it
// to detect existing gents-generated files versus hand-written TS.
const generatedHeader = "// Code generated by github.com/mmalcek/gents; DO NOT EDIT."

func main() {
	os.Exit(run(os.Args[1:], os.Stderr))
}

// run is the testable entry point. Flag parsing, validation, and the
// library call all live here so tests can drive it with a synthetic args
// slice and inspect stderr. Panics from the library are caught and
// printed as single-line errors — never leaks a Go stack trace to the
// user through a //go:generate pipeline.
func run(args []string, stderr io.Writer) (code int) {
	defer func() {
		r := recover()
		if r == nil {
			return
		}
		// Our deliberate panics (emitter.panicAt) always carry an error
		// value — print the message cleanly and exit 1. Anything else
		// (nil deref, index out of range, etc.) is an internal bug;
		// re-panic so Go's default handler prints a full stack trace
		// for debugging and bug reports.
		if err, ok := r.(error); ok {
			fmt.Fprintln(stderr, err)
			code = 1
			return
		}
		panic(r)
	}()

	fs := flag.NewFlagSet("gents", flag.ContinueOnError)
	fs.SetOutput(stderr)

	in := fs.String("in", "", "Go source file or directory to process. Directories are walked recursively. Defaults to the current directory.")
	out := fs.String("out", "", "TypeScript file to write (required)")
	strip := fs.String("strip", "t", "Prefix stripped from Go struct names when building factory function names (e.g. default \"t\" turns tFoo into newFoo). The TS interface name itself is always emitted verbatim from the Go struct name. Pass -strip=\"\" to keep the prefix on the factory too.")
	force := fs.Bool("force", false, "Overwrite the output file even if it wasn't generated by gents")
	typeMap := mapFlag{}
	fs.Var(typeMap, "map", "Custom type mapping GoType=TSType (e.g. uuid.UUID=string). Repeatable. Zero values inferred from TS type.")

	if err := fs.Parse(args); err != nil {
		// flag.ContinueOnError already wrote usage/error to stderr.
		return 2
	}

	if *out == "" {
		fmt.Fprintln(stderr, "-out is required")
		fs.Usage()
		return 1
	}

	path := *in
	if path == "" {
		path = "."
	}
	info, err := os.Stat(path)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}

	opts := gents.Options{Strip: *strip, TypeMap: typeMap}
	var src string
	if info.IsDir() {
		src, err = gents.GenerateDir(path, opts)
	} else {
		src, err = gents.Generate(path, opts)
	}
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	if src == "" {
		// No marked structs in input; don't create an empty output file.
		return 0
	}
	if err := safeWrite(*out, []byte(src), *force); err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	return 0
}

// safeWrite writes data to path, but refuses to overwrite an existing file
// whose first line isn't the gents-generated header — unless force is
// true. Also ensures the parent directory exists so first-time users
// writing to a path like ../client/types/foo.ts don't hit "no such file
// or directory" when the target dir hasn't been created yet.
func safeWrite(path string, data []byte, force bool) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if info, err := os.Stat(path); err == nil && !info.IsDir() && !force {
		first, err := readFirstLine(path)
		if err != nil {
			return err
		}
		if strings.TrimRight(first, "\r\n") != generatedHeader {
			return fmt.Errorf("%s exists and is not a gents-generated file (first line does not match the expected header); pass -force to overwrite", path)
		}
	}
	return os.WriteFile(path, data, 0o644)
}

func readFirstLine(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	if sc.Scan() {
		return sc.Text(), nil
	}
	if err := sc.Err(); err != nil {
		return "", err
	}
	return "", nil
}
