// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Nested {
  b: string
}

export function newNested(): Nested {
  return {
    b: '',
  }
}

export interface Foo {
  a: string
  nested: Nested
  name: string
}

export function newFoo(): Foo {
  return {
    a: '',
    nested: newNested(),
    name: '',
  }
}
