// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Header {
  'content-type': string
  '123status': number
  'x.foo': string
}

export function newHeader(): Header {
  return {
    'content-type': '',
    '123status': 0,
    'x.foo': '',
  }
}
