// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: b_user.go) */
export interface User {
  id: string
  created: Date | null
}

export function newUser(): User {
  return {
    id: '',
    created: null,
  }
}
