// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Foo {
  tags: Record<string, string>
  items: Record<string, Item>
  flags: Record<string, boolean | null>
}

export function newFoo(): Foo {
  return {
    tags: {},
    items: {},
    flags: {},
  }
}

export interface Item {
  value: string
}

export function newItem(): Item {
  return {
    value: '',
  }
}
