// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Ids {
  user: string
  maybe: string | null
  enabled: string
  toggle: string | null
  price: string
  wait: string
  plain: number
}

export function newIds(): Ids {
  return {
    user: '0',
    maybe: null,
    enabled: 'false',
    toggle: null,
    price: '0',
    wait: '0',
    plain: 0,
  }
}
