// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Foo {
  anything: unknown
  iface: unknown
}

export function newFoo(): Foo {
  return {
    anything: null,
    iface: null,
  }
}
