// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Foo {
  anything: unknown
  iface: unknown
}

export function newFoo(): Foo {
  return {
    anything: null,
    iface: null,
  }
}
