// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/**
 * tstring strips (with -strip=t) to the factory base name "string". A
 * user mapping to TS "string" must NOT be reported as a collision: the
 * emitted interface is named "tstring", and factory names live in value
 * space where type expressions cannot collide.
 * (source: input.go)
 */
export interface tstring {
  value: string
}

export function newstring(): tstring {
  return {
    value: '',
  }
}

/** (source: input.go) */
export interface tItem {
  id: string
}

export function newItem(): tItem {
  return {
    id: '',
  }
}
