// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Item {
  id: string
  name: string
}

export function newItem(): Item {
  return {
    id: '',
    name: '',
  }
}
