// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Foo {
  a: string
  b: string
  c: string
}

export function newFoo(): Foo {
  return {
    a: '',
    b: '',
    c: '',
  }
}
