// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Foo {
  required: string
  optional?: string
  BareName?: string
  NoTag: string
  EmptyName: string
}

export function newFoo(): Foo {
  return {
    required: '',
    NoTag: '',
    EmptyName: '',
  }
}
