// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/**
 * Permission bits for access profiles.
 * (source: input.go)
 */
/** view or list records */
export const PermRead = 1
/** create records */
export const PermCreate = 2
export const PermUpdate = 4
export const PermDelete = 8
export const PermAll = PermRead | PermCreate | PermUpdate | PermDelete

/** (source: input.go) */
/** Role assigned when no profile matches. */
export const DefaultRole = 'guest'
export const MaxItems = 1 << 10
export const Threshold = -0.5
export const LegacyOctal = 15
export const FeatureOn = true
export const Combined = (PermRead | PermCreate) & PermAll
