// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Session {
  id: string
  entry_type: 'manual' | 'automatic'
  level: 0 | 1 | 2
  meta: Record<string, string>
  expire?: string | null
}

export function newSession(): Session {
  return {
    id: '',
    entry_type: 'manual',
    level: 0,
    meta: {},
  }
}
