// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface Event {
  id: string
  created_at?: string
  retries?: number
  label?: string
}

export function newEvent(): Event {
  return {
    id: '',
  }
}
