// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface Foo {
  created: string
  updated: string | null
  name: string | null
  scores: number[]
}

export function newFoo(): Foo {
  return {
    created: '',
    updated: null,
    name: null,
    scores: [],
  }
}
