// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: input.go) */
export interface User {
  id: string
  score: number
  active: boolean
}

export function newUser(): User {
  return {
    id: '',
    score: 0,
    active: false,
  }
}
