// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

/** (source: a_user.go) */
export interface User {
  id: string
  profile: Profile
}

export function newUser(): User {
  return {
    id: '',
    profile: newProfile(),
  }
}

/** (source: b_profile.go) */
export interface Profile {
  bio: string
}

export function newProfile(): Profile {
  return {
    bio: '',
  }
}
