// Code generated by github.com/mmalcek/gents; DO NOT EDIT.

export interface User {
  id: string
  profile: Profile
}

export function newUser(): User {
  return {
    id: '',
    profile: newProfile(),
  }
}

export interface Profile {
  bio: string
}

export function newProfile(): Profile {
  return {
    bio: '',
  }
}
